post_index:
    path:     /{currentPage}
    defaults: { _controller: "PostsBundle:Post:index",currentPage:1}
    requirements:
                methods:  GET
                post_id: \d+

post_show:
    path:     /{id}/show
    defaults: { _controller: "PostsBundle:Post:show" }
    methods:  GET

post_new:
    path:     /new/{subj}
    defaults: { _controller: "PostsBundle:Post:new" }
    requirements:
                methods:  POST
                post_id: \w+
    #вот тута добавить дефолтный 0 для subj

post_edit:
    path:     /{id}/edit
    defaults: { _controller: "PostsBundle:Post:edit" }
    methods:  [GET, POST]

post_delete:
    path:     /{id}/delete
    defaults: { _controller: "PostsBundle:Post:delete" }
    methods:  DELETE


