admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Index:index}
admin_get_json:
    path: /posts/{currentPage}
    defaults: { _controller: AdminBundle:Index:getAllPosts, currentPage:1}
    requirements:
        methods: GET
        currentPage: \d+



