#file_upload:
    #resource: "@FileUploadBundle/Resources/config/routing.yml"
    #prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

posts:
    resource: "@PostsBundle/Resources/config/routing.yml"
    prefix:   /post

#todo:: так можно переделать нижний туду
test:
    resource: "@PostsBundle/Resources/config/routing/subject.yml"
    prefix:   /

#todo:: удалить
#subject:
#    path: /{subj}
#    defaults: { _controller: PostsBundle:Subject:index }
#    requirements:
#                    methods:  GET
#                    post_id: \w
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"




