user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

posts:
    resource: "@PostsBundle/Resources/config/routing.yml"
    prefix:   /post

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
