# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
      file_uploader:
          class: FileUploadBundle\Service\FileUploader
          arguments: ["%files_directory%"]

imports:
    - { resource: "@PostsBundle/Resources/config/services.yml" }
