services:
    login_handler:
      class: UserBundle\Listeners\LoginListener
      arguments:
          container : "@service_container"
          router: "@router"
      tags:
          - {name: kernel.login_hendler }
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
