posts_post:
    resource: "@PostsBundle/Resources/config/routing/post.yml"
    prefix:   /

posts_comment:
    resource: "@PostsBundle/Resources/config/routing/comment.yml"
    prefix:   /comment


subject:
    path: /{subj}
    defaults: { _controller: "PostsBundle:Subject:index"}