posts_post:
    resource: "@PostsBundle/Resources/config/routing/post.yml"
    prefix:   /

posts_comment:
    resource: "@PostsBundle/Resources/config/routing/comment.yml"
    prefix:   /comment

#posts_subject:
#    resource: "@PostsBundle/Resources/config/routing/subject.yml"
#    prefix:   /

#test:
#    requirements: {_controller: "AppBundle:Default:test"}
#    path:   /t
