posts_post:
    resource: "@PostsBundle/Resources/config/routing/post.yml"
    prefix:   /post

posts_homepage:
    path:     /
    defaults: { _controller: PostsBundle:Default:index }


posts_comment:
        resource: "@PostsBundle/Resources/config/routing/comment.yml"
        prefix:   /comment
