services:
    posts.controller:
        class: PostsBundle\Service\PostService
        arguments: ['@form.factory', '@router', '@form.type.form']
        #arguments : "@service_id", "plain_value", "%parameter%"
