<?php

namespace PostsBundle\Repository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentsForPost($postId)
    {
        $qb = $this->createQueryBuilder('c')->select('c')
            ->where('c.post = :post_id')
            ->addOrderBy('c.createAt')
            ->setParameter('post_id', $postId);


        return $qb->getQuery()->getResult();
    }
}
