<?php

namespace PostsBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByPage($currentPage = 1, $limit = 10)
    {
        $query = $this->createQueryBuilder('post')
            ->select('post')
            ->setFirstResult($limit * ($currentPage - 1))
            ->setMaxResults($limit)
            ->getQuery();

        return new Paginator($query, $fetchJoinCollection = false);
    }

    public function getTotal()
    {
        return $this->createQueryBuilder('post')->select('COUNT(post)')
            ->getQuery()
            ->getSingleScalarResult();


    }

}
