<?php

namespace PostsBundle\Repository;
use Doctrine\ORM\Query\Expr;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * SubjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySubj($subj = "subj", $currentPage = 1, $limit = 10)
    {

        /*дописать номальный запрос через join
            для этого потренироваться на кошках
        */

            $query = $this->createQueryBuilder('post')
                ->select('p')
                ->from('PostsBundle:Post', 'p')
                ->setFirstResult($limit * ($currentPage - 1))
                ->setMaxResults($limit)
                ->orderBy('p.id','DESC')
                ->getQuery();

            return new Paginator($query, $fetchJoinCollection = false);
    }

        public function getTotal()
    {
        return $this->createQueryBuilder('post')->select('COUNT(post)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    /*
     * public function findAllByPage($currentPage = 1, $limit = 10)
    {
        $query = $this->createQueryBuilder('post')
            ->select('post')
            ->setFirstResult($limit * ($currentPage - 1))
            ->setMaxResults($limit)
            ->orderBy('post.id','DESC')
            ->getQuery();

        return new Paginator($query, $fetchJoinCollection = false);
    }

    public function getTotal()
    {
        return $this->createQueryBuilder('post')->select('COUNT(post)')
            ->getQuery()
            ->getSingleScalarResult();


    }*/
}
