<?php

namespace PostsBundle\Repository;

use Doctrine\ORM\Query\Expr;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * SubjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Возвращает посты определеного обсуждения.
     *
     * @param string $subj
     * @param int $currentPage
     * @param int $limit
     * @return Paginator
     */
    public function findBySubj($subj = "subj", $currentPage = 1, $limit = 10)
    {

        $query = $this->createQueryBuilder('post')
            ->select('p')
            ->from('PostsBundle:Post', 'p')
            ->setFirstResult($limit * ($currentPage - 1))
            ->setMaxResults($limit)
            ->orderBy('p.id', 'DESC')
            ->getQuery();

        return new Paginator($query, $fetchJoinCollection = false);
    }

    /**
     * Возвращает количество постов.
     * @return int
     */
    public function getTotal()
    {
        return $this->createQueryBuilder('post')->select('COUNT(post)')
            ->getQuery()
            ->getSingleScalarResult();
    }


}
